### ISSUE TITLE
Bug 4: User Enquiry Not Showing.

### ISSUE THREAD

**Issue by Nimesh-shta** [sujan-0/pet-adoption-system-html-css-js-php#5]
![image](https://github.com/sujan-0/pet-adoption-system-html-css-js-php/assets/127822872/b66e1a7d-f54b-4462-bc1a-c51a79d8e44e)
![image](https://github.com/sujan-0/pet-adoption-system-html-css-js-php/assets/127822872/b4f88986-df6b-4855-bbe0-809b610166a3)

**Comment by sujan-0** [comment]
It was due to error in fetching.
It's  working properly Now✅
