### ISSUE TITLE
Bug 5: Payment site not opening in user side.

### ISSUE THREAD

**Issue by Nimesh-shta** [sujan-0/pet-adoption-system-html-css-js-php#6]
![image](https://github.com/sujan-0/pet-adoption-system-html-css-js-php/assets/127822872/c7b56333-890d-47c8-9f7b-00a7e0155091)
![image](https://github.com/sujan-0/pet-adoption-system-html-css-js-php/assets/127822872/73f08dc2-bea3-4954-b31c-93ef9135c83a)

**Comment by sujan-0** [comment]
Now it's working.
