### ISSUE TITLE
Product Add

### ISSUE THREAD

**Issue by LMvibek10** [sujan-0/pet-adoption-system-html-css-js-php#8]
When not entering any data and clicking add product. The product added message is shown.
![sujan2](https://github.com/sujan-0/pet-adoption-system-html-css-js-php/assets/119830540/77194b78-89dc-47c1-b52f-f97c3eea73a4)
![sujan](https://github.com/sujan-0/pet-adoption-system-html-css-js-php/assets/119830540/2027d38d-e191-4998-8eb7-2a2198292172)

**Comment by sujan-0** [comment]
Ok thank You for letting know 
I've already fixed please revisit the page
